services:
  app:
    image: app-image
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: 'loopfiy1.czo0oemmwl67.ap-northeast-2.rds.amazonaws.com'
      DB_PORT: 5432
      DB_USER: loopfiy
      DB_PASS: aaaa4321!
      DB_NAME: loopfiy
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80' # 호스트 포트:컨테이너 포트
    depends_on:
      - app # nginx는 app이 먼저 시작된 후에 실행
    volumes:
      - ./ebextensions/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

nginx:
    image: nginx:latest
    ports:
      - '80:80' # 호스트 포트:컨테이너 포트
    depends_on:
      - app # nginx는 app이 먼저 시작된 후에 실행
    volumes:
      - .ebextensions/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
# networks:
#   app-network:
#     driver: bridge