services:
  app:
    image: app-image
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: pg-3041fi.vpc-pub-cdb-kr.ntruss.com
      DB_PORT: 5432
      DB_USER: chainedtogether
      DB_PASS: aaaa4321!
      DB_NAME: loopfiy
