version: '3'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgresDB
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=${DB_USERNAME} # .env 파일에서 가져오기
      - DB_PASSWORD=${DB_PASSWORD} # .env 파일에서 가져오기
      - DB_NAME=${DB_NAME} # .env 파일에서 가져오기
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
