services:
  app:
    image: app-image # 이미지 이름 설정
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      DB_HOST: 'loopfiy.cjggiigww7oa.us-east-1.rds.amazonaws.com'
      DB_PORT: 5432
      DB_USER: loopfiy
      DB_PASS: aaaa4321!
      DB_NAME: loopfiy
    networks:
      - app-network

  nginx-rtmp:
    build:
      context: ./rtmp
    ports:
      - '1935:1935' # RTMP 스트리밍 포트
    volumes:
      - ./hls:/tmp/hls
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - nginx-rtmp
      - app
    volumes:
      - ./ebextensions/nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/tmp/hls
    entrypoint: >
      /bin/sh -c "while ! curl -s http://app:3000 > /dev/null; do sleep 1; done; nginx -t && nginx -g 'daemon off;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
