services:
  app:
    image: app-image
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: pg-3041fi.vpc-pub-cdb-kr.ntruss.com
      DB_PORT: 5432
      DB_USER: chainedtogether
      DB_PASS: aaaa4321!
      DB_NAME: loopfiy

nginx:
    image: nginx:latest
    ports:
      - '80:80' # 호스트 포트:컨테이너 포트
    depends_on:
      - app # nginx는 app이 먼저 시작된 후에 실행
    volumes:
      - .ebextensions/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge