# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: app
#     environment:
#       - DB_HOST= ${DB_HOST}
#       - DB_PORT=5432
#       - DB_USER=${DB_USERNAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_NAME=${DB_NAME}
#       - PORT=${PORT}
#       - NODE_ENV=production
#     ports:
#       - '3000:3000'
#     volumes:
#       - ./src:/app/src

services:
  app:
    image: app-image # 이미지 이름 설정
    build:
      context: .
      dockerfile: Dockerfile # 명시적으로 Dockerfile 사용
    ports:
      - '3000:3000'
    environment:
      DB_HOST: 'loopfiy1.czo0oemmwl67.ap-northeast-2.rds.amazonaws.com'
      DB_PORT: 5432
      DB_USER: loopfiy
      DB_PASS: aaaa4321!
      DB_NAME: loopfiy
    volumes:
      - ./src:/usr/src/app # 소스코드 공유를 위해 추가 (필요시)

  nginx-rtmp:
    build:
      context: ./rtmp # nginx-rtmp 디렉토리에서 빌드
    ports:
      - '1935:1935' # RTMP 스트리밍 포트
      - '8080:8080' # NGINX 관리 페이지 포트
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80' # 호스트 포트:컨테이너 포트
    depends_on:
      - app # nginx는 app이 먼저 시작된 후에 실행
    volumes:
      - ./ebextensions/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
