services:
  app:
    image: app-image # 이미지 이름 설정
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DB_HOST: 'loopfiy1.czo0oemmwl67.ap-northeast-2.rds.amazonaws.com'
      DB_PORT: 5432
      DB_USER: loopfiy
      DB_PASS: aaaa4321!
      DB_NAME: loopfiy
      REDIS_URL: 'redis://redis:6379' # Redis URL 설정
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-network

  nginx-rtmp:
    build:
      context: ./rtmp
    ports:
      - '1935:1935' # RTMP 스트리밍 포트
      - '8888:8080' # NGINX 관리 페이지 포트
    environment:
      - BEANSTALK_ADDRESS=http://loopfiy2.ap-northeast-2.elasticbeanstalk.com
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./rtmp/cert:/rtmp/cert
      - ./ebextensions/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: >
      /bin/sh -c "while ! curl -s http://app:3000 > /dev/null; do sleep 1; done; nginx -t && nginx -g 'daemon off;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
