name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: ${{ secrets.KSR_AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.KSR_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.KSR_AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: ${{ secrets.KSR_ECR_REPOSITORY_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.KSR_AWS_REGION }} | docker login --username AWS --password-stdin 022499011115.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY }}

      - name: Build, tag, and push Docker image
        env:
          AWS_REGION: ${{ secrets.KSR_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.KSR_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KSR_AWS_SECRET_ACCESS_KEY }}
        run: |
          # Docker 이미지 빌드
          docker build -t ${{ secrets.KSR_ECR_REPOSITORY }} .

          # Docker 이미지 태그
          DOCKER_IMAGE_ID=$(docker images -q ${{ secrets.KSR_ECR_REPOSITORY }}:latest)
          docker tag $DOCKER_IMAGE_ID 022499011115.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY }}:latest

          # Docker 이미지 푸시
          docker push 022499011115.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY }}:latest

      # 문제 해결 단계
      - name: Issue Resolution Steps  # 문제 해결 단계
        run: |
          # ECR에 올바른 태그 존재 여부 확인
          docker images

          # 태그 생성 및 사용
          DOCKER_IMAGE_ID=$(docker images -q ${{ secrets.KSR_ECR_REPOSITORY }}:latest)
          docker tag $DOCKER_IMAGE_ID 022499011115.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY }}:latest

          # 로컬 이미지 존재 확인
          docker images


          # Docker 인증 및 ECR 로그인 확인
          aws ecr get-login-password --region ${{ secrets.KSR_AWS_REGION }} | docker login --username AWS --password-stdin 022499011115.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY }}

          # 필요 없는 이전 태그 삭제 및 재시도
          PREVIOUS_TAG=$(docker images --filter "reference=022499011115.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY }}:*" -q | grep -v $DOCKER_IMAGE_ID)
          if [ -n "$PREVIOUS_TAG" ]; then
            docker rmi 022499011115.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY }}:$PREVIOUS_TAG
          fi
