name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev # dev 브랜치에 푸시될 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2 # AWS 리전 (예: ap-northeast-2)
      ECR_REPOSITORY: 'your-ecr-repository-name'
      EB_ENV_NAME: Loopfiy-env-1
      AWS_ACCESS_KEY_ID: ${{ secrets.EB_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EB_AWS_SECRET_ACCESS_KEY }}

    steps:
      # 1. Checkout 코드
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.EB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.EB_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 3. Ensure ECR Repository Exists
      - name: Create ECR Repository if it does not exist
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY || \
          aws ecr create-repository --repository-name $ECR_REPOSITORY --region ap-northeast-2
        env:
          AWS_REGION: ap-northeast-2
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}

      # 4. Install Dependencies
      - name: Install Dependencies
        run: |
          npm ci

      # 5. Run Tests
      - name: Run Tests
        run: |
          npm test

      # 6. Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 7. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .

      # 8. Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      # 9. Deploy updated image to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment --environment-name $EB_ENV_NAME --version-label latest
