name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ${{ secrets.KSR_AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.KSR_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.KSR_AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: ${{ secrets.KSR_ECR_REPOSITORY_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 022499011115.dkr.ecr.ap-northeast-2.amazonaws.com/loopfiy-ecr

      # 3. Build, tag, and push the Docker image
      - name: Build, tag, and push Docker image
        env:
          AWS_REGION: ${{ secrets.KSR_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.KSR_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KSR_AWS_SECRET_ACCESS_KEY }}
        run: |
          # Build Docker image
          docker build -t ${{ secrets.KSR_ECR_REPOSITORY_NAME }} .

          # Tag Docker image
          docker tag ${{ secrets.KSR_ECR_REPOSITORY_NAME }}:latest ${{ secrets.KSR_AWS_ACCESS_KEY }}.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY_NAME }}:latest

          # Push Docker image to ECR
          docker push ${{ secrets.KSR_AWS_ACCESS_KEY }}.dkr.ecr.${{ secrets.KSR_AWS_REGION }}.amazonaws.com/${{ secrets.KSR_ECR_REPOSITORY_NAME }}:latest
