name: Deploy to AWS ECR and Elastic Beanstalk

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: ${{ secrets.KSR_AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.KSR_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.KSR_AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: ${{ secrets.KSR_ECR_REPOSITORY_NAME }}
  AWS_ACCOUNT_ID: ${{ secrets.KSR_AWS_ACCOUNT_ID }}
  EB_APP_NAME: ${{ secrets.KSR_EB_APP_NAME }}
  EB_ENV_NAME: ${{ secrets.KSR_EB_ENV_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Node.js 22버전인데 에러발생시 버전다운 해야함

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }} .

      - name: Tag Docker Image
        run: |
          DOCKER_IMAGE_ID=$(docker images -q ${{ env.ECR_REPOSITORY }}:latest)
          docker tag $DOCKER_IMAGE_ID ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt remove python3-urllib3
          sudo pip install awsebcli

      - name: Remove Old Containers and Images on Elastic Beanstalk Instance
        run: |
            ssh -i ~/.ssh/my-key.pem ec2-user@13.125.148.162 "
              docker ps -q | xargs -r docker stop &&
              docker ps -aq | xargs -r docker rm &&
              docker images -q | xargs -r docker rmi -f

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.KSR_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KSR_AWS_SECRET_ACCESS_KEY }}
        run: |
          eb init -p docker ${{ env.EB_APP_NAME }} --region ${{ env.AWS_REGION }}
          eb deploy ${{ env.EB_ENV_NAME }}