name: single-instance
 
on:
  push:
    branches: 
      - dev
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
 
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests (optional)
        run: npm test
        
      - name: Configure AWS credentials #3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.REGION }}
          mask-aws-account-id: 'false'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
 
      - name: Login to Amazon ECR #4
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
 
      - name: Build, tag, and push docker image to Amazon ECR #5
        run: |
          docker build -t ${{ secrets.AWS_ECR_URL }}/elastic-beanstalk:latest .
          docker push ${{ secrets.AWS_ECR_URL }}/elastic-beanstalk:latest
 
      - name: Create Dockerrun.aws.json #6
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "'${{ secrets.AWS_ECR_URL }}/elastic-beanstalk:latest'",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "8080",
                "HostPort": "80"
              }
            ]
          }' > Dockerrun.aws.json
 
          
      - name: Get current time #7
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"
 
      - name: Generate deployment package #8
        run: |
          mkdir -p deploy
          cp Dockerrun.aws.json deploy/Dockerrun.aws.json
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r deploy.zip .
 
      - name: Deploy to EB #9
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: elastic-beanstalk
          environment_name: elastic-beanstalk-dev
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ${{ secrets.REGION }}
          existing_bucket_name: elastic-beanstalk-deploy-zip
          deployment_package: deploy/deploy.zip