name: CI/CD Pipeline

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm test # 테스트 실행

  build-and-push:
    needs: test # test 잡 성공 후 실행
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t my-app .

      # Docker 이미지 푸시 (선택적)
      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag my-app $DOCKER_USERNAME/my-app:latest
          docker push $DOCKER_USERNAME/my-app:latest
