# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

# 잡정의
jobs:
  build:
    # 러너 정의
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      # Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t my-app .

      # Docker 컨테이너 실행
      - name: Run Docker container
        run: |
          docker run -d --name my-app-container my-app

      # Docker 컨테이너에서 테스트 실행
      - name: Run tests inside Docker container
        run: |
          docker exec my-app-container npm test

      # Docker 컨테이너 종료
      - name: Stop Docker container
        run: |
          docker stop my-app-container
          docker rm my-app-container

      # Docker 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag my-app $DOCKER_USERNAME/my-app:latest
          docker push $DOCKER_USERNAME/my-app:latest
